1. Importar pacotes

In [2]:
import pandas as pd
import requests

2. Definir a URL

In [4]:
server_url = "https://dadosabertos.compras.gov.br/modulo-material/2_consultarClasseMaterial"

3. Fazer a requisição para obter os dados

In [5]:
pagina = 1
paginas_restantes = 1
resultado_classe = []

while paginas_restantes != 0:
    
    response = requests.get(server_url, params={'pagina': pagina})

    if response.status_code == 200:
        json_response = response.json()
        print(json_response)
        resultado_classe.extend(json_response["resultado"])
        paginas_restantes = json_response["paginasRestantes"]
        pagina = pagina + 1
    else:
        print("Erro: ", response.text)
        paginas_restantes = 0

resultado_classe

{'resultado': [{'codigoClasse': 1005, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ATÉ 120MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1010, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 30MM ATÉ 75MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1015, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 75MM ATÉ 125MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1020, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 125MM ATÉ 150MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1025, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 150MM ATÉ 200MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1030, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 200MM ATÉ 300MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1035, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 300MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1040, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAMENTO E EQUIPAMENTOS DE GUERRA QUÍMICA', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1045, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'LANÇADORES DE TORPEDOS E DE BOMBAS DE PROFUNDIDADE', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1055, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'LANÇADORES DE FOGUETES E PIROTÉCNICOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1070, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'REDES SUBMARINAS DE DEFESA DE PORTOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1075, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'EQUIPAMENTOS DE DESMAGNETIZAÇÃO E DE VARREDURA DE MINAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1080, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'EQUIPAMENTOS DE CAMUFLAGEM E DE DISSIMULAÇÃO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1090, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'CONJUNTOS INTERCAMBIÁVEIS DE DUAS OU MAIS CLASSES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1095, 'codigoGrupo': 10, 'nomeGrupo': 'ARMAMENTO', 'nomeClasse': 'ARMAMENTOS DIVERSOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1105, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'BOMBAS NUCLEARES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1110, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'PROJÉTEIS NUCLEARES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1115, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'OGIVAS NUCLEARES E SEÇÕES DE OGIVAS NUCLEARES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1120, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'BOMBAS NUCLEARES DE PROFUNDIDADE', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1125, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'CARGAS NUCLEARES DE DEMOLIÇÃO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1127, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'FOGUETES NUCLEARES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1130, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'CONJUNTOS DE CONVERSÃO PARA ARMAMENTO NUCLEAR', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1135, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'DISPOSITIVOS DE DETONAÇÃO E DISPARO DE ARMAMENTO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1140, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'COMPONENTES NUCLEARES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1145, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'COMPONENTES EXPLOSIVOS E PIROTÉCNICOS DE ARMAMENTO NUCLEAR', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1190, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'EQUIPAMENTO ESPECIALIZADO DE MANUSEIO E ENSAIO DE  ARMAMENTONUCLEAR', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1195, 'codigoGrupo': 11, 'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES', 'nomeClasse': 'MATERIAL BÉLICO NUCLEAR DIVERSOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1210, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'DIRETORAS DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1220, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'DISPOSITIVOS E CORRETORES DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1230, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'SISTEMAS COMPLETOS DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1240, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTOS ÓTICOS DE VISADA E MEDIÇÃO DE DISTÂNCIA', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1250, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'MECANISMOS DE ESTABILIZAÇÃO E CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1260, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTO DE DESIGNAÇÃO E INDICAÇÃO DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1265, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTO DE RECEPÇÃO E TRANSMISSÃO DE  CONTROLE  DE  TIRO(EXCETO DE AERONAVE)', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1270, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'COMPONENTES DE CONTROLE DE TIRO DE AERONAVES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1280, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'COMPONENTES DE CONTROLE DE TIRO EM AERONAVES DE BOMBARDEIO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1285, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTO RADAR DE CONTROLE DE TIRO (EXCETO DE AERONAVES)', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1287, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTO SONAR DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1290, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTOS DIVERSOS DE CONTROLE DE TIRO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1295, 'codigoGrupo': 12, 'nomeGrupo': 'EQUIPAMENTOS DE TIRO', 'nomeClasse': 'EQUIPAMENTO DE CONTROLE DE TIRO DIVERSOS', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1305, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MUNIÇÃO DE CALIBRE ATÉ 30 MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1310, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 30 MM ATÉ 75 MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1315, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 75MM ATÉE 125MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1320, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 125 MM', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1325, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'BOMBAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1330, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'GRANADAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1336, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'OGIVAS E COMPONENTES EXPLOSIVOS DE MISSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1337, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'UNIDADES DE PROPULSAO EXPLOSIVA A COMBUSTIVEL SOLIDO DE VEICULOS ESPACIAIS E MISSEIS GUIADOS E SEUS COMPONENTES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1338, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'UNIDADES DE PROPULSAO INERTES A COMBUSTIVEL SOLIDO DE VEICULOS ESPACIAIS E MISSEIS GUIADOS E SEUS COMPONENTES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1340, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'ROJÕES, FOGUETES, MUNIÇÃO E COMPONENTES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1345, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MINAS TERRESTRES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1346, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MUNIÇÕES DE CONTROLE À DISTÂNCIA', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1350, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES INERTES DE MINA SUBMARINA', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1351, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES EXPLOSIVOS DE MINAS SUBMARINAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1352, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'DISPOSITIVOS INERTES DE MINAS SUBAQUÁTICAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1353, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'DISPOSITIVOS EXPLOSIVOS DE MINAS SUBAQUÁTICAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1355, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES INERTES DE TORPEDOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1356, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES EXPLOSIVOS DE TORPEDOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1360, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES INERTES DE CARGAS DE PROFUNDIDADE', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1361, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES EXPLOSIVOS DE BOMBAS DE PROFUNDIDADE', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1367, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'CONJUNTOS E EQUIPAMENTOS TÁTICOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1370, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'PIROTECNICOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1375, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'MATERIAIS DE DEMOLIÇÃO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1376, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'EXPLOSIVOS A GRANEL', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1377, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'DISPOSITIVOS ACIONADOS POR PROPELENTES E CARTUCHOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1380, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'AGENTES BIOLOGICOS DE USO MILITAR', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1385, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'EQUIPAMENTOS E FERRAMENTAS PARA MANUSEIO DE EXPLOSIVO NA SU-PERFÍCIE', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1386, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'EQUIPAMENTOS E FERRAMENTAS PARA MANUSEIO DE  EXPLOSIVO  SUB-MERSO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1390, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'ESPOLETAS E ESTOPILHAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1395, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'COMPONENTES DIVERSOS DE MUNIÇÃO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1398, 'codigoGrupo': 13, 'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS', 'nomeClasse': 'EQUIPAMENTOS ESPECIALIZADOS PARA MANUSEIO E CONSERVACAO DE MUNICAO', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1410, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1420, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'COMPONENTES DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1425, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'SISTEMAS COMPLETOS DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1427, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'SUBSISTEMAS DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1430, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'SISTEMA DE CONTROLE REMOTO DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1440, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'LANÇADORES DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1450, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'EQUIPAMENTO PARA MANUSEIO DE MANUTENÇÃO DE MÍSSEIS GUIADOS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1495, 'codigoGrupo': 14, 'nomeGrupo': 'MÍSSEIS GUIADOS', 'nomeClasse': 'MISSEIS GUIADOS DIVERSOS', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1505, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'AERONAVES', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1510, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'AERONAVES DE ASAS FIXAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1515, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'HELICES DE AERONAVES E COMPONENTES', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1520, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'AERONAVES DE ASA ROTATIVAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1525, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'COMPONENTES DE SISTEMA DE FREIOS E RODAS', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1530, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'COMPNENTES DE SISTEMA HIDRAULICO, DE VACUO E  DEGELAMENTO', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1535, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'COMPONENTE DE SISTEMAS DE CONDICIONAMENTO  DE  AR,DO AQUECIMENTO E DE PRESSURIZACAO', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1540, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'PLANADORES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1550, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'AERONAVES TELEGUIADAS', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1560, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'COMPONENTES ESTRUTURAIS DE AERONAVES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1595, 'codigoGrupo': 15, 'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS', 'nomeClasse': 'AERONAVES E COMPONENTES ESTRUTURAIS DIVERSOS', 'statusClasse': False, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1610, 'codigoGrupo': 16, 'nomeGrupo': 'COMPONENTES E ACESSORIOS DE AERONAVES', 'nomeClasse': 'HELICES DE AERONAVES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1615, 'codigoGrupo': 16, 'nomeGrupo': 'COMPONENTES E ACESSORIOS DE AERONAVES', 'nomeClasse': 'PÁS DE ROTOR DE HELICOPTERO, MECANISMOS DE TRANSMISSÃO E    COMPONENTES', 'statusClasse': True, 'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'}, {'codigoClasse': 1620, 'codigoGrupo': 16, 'nomeGrupo': 'COMPONENTES E ACESSORIOS DE AERONAVES', 'nomeClasse': 'COMPONENTES DE TREM DE POUSO DE AERONAVE', 'statusClasse': True, 'dataHoraAtua

[{'codigoClasse': 1005,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ATÉ 120MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1010,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 30MM ATÉ 75MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1015,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 75MM ATÉ 125MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1020,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 125MM ATÉ 150MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1025,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 150MM ATÉ 200MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1030,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 200MM ATÉ 300MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1035,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAS DE FOGO DE CALIBRE ACIMA DE 300MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1040,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAMENTO E EQUIPAMENTOS DE GUERRA QUÍMICA',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1045,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'LANÇADORES DE TORPEDOS E DE BOMBAS DE PROFUNDIDADE',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1055,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'LANÇADORES DE FOGUETES E PIROTÉCNICOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1070,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'REDES SUBMARINAS DE DEFESA DE PORTOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1075,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'EQUIPAMENTOS DE DESMAGNETIZAÇÃO E DE VARREDURA DE MINAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1080,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'EQUIPAMENTOS DE CAMUFLAGEM E DE DISSIMULAÇÃO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1090,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'CONJUNTOS INTERCAMBIÁVEIS DE DUAS OU MAIS CLASSES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1095,
  'codigoGrupo': 10,
  'nomeGrupo': 'ARMAMENTO',
  'nomeClasse': 'ARMAMENTOS DIVERSOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1105,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'BOMBAS NUCLEARES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1110,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'PROJÉTEIS NUCLEARES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1115,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'OGIVAS NUCLEARES E SEÇÕES DE OGIVAS NUCLEARES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1120,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'BOMBAS NUCLEARES DE PROFUNDIDADE',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1125,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'CARGAS NUCLEARES DE DEMOLIÇÃO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1127,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'FOGUETES NUCLEARES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1130,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'CONJUNTOS DE CONVERSÃO PARA ARMAMENTO NUCLEAR',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1135,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'DISPOSITIVOS DE DETONAÇÃO E DISPARO DE ARMAMENTO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1140,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'COMPONENTES NUCLEARES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1145,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'COMPONENTES EXPLOSIVOS E PIROTÉCNICOS DE ARMAMENTO NUCLEAR',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1190,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'EQUIPAMENTO ESPECIALIZADO DE MANUSEIO E ENSAIO DE  ARMAMENTONUCLEAR',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1195,
  'codigoGrupo': 11,
  'nomeGrupo': 'MATERIAIS BÉLICOS NUCLEARES',
  'nomeClasse': 'MATERIAL BÉLICO NUCLEAR DIVERSOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1210,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'DIRETORAS DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1220,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'DISPOSITIVOS E CORRETORES DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1230,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'SISTEMAS COMPLETOS DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1240,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTOS ÓTICOS DE VISADA E MEDIÇÃO DE DISTÂNCIA',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1250,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'MECANISMOS DE ESTABILIZAÇÃO E CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1260,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTO DE DESIGNAÇÃO E INDICAÇÃO DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1265,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTO DE RECEPÇÃO E TRANSMISSÃO DE  CONTROLE  DE  TIRO(EXCETO DE AERONAVE)',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1270,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'COMPONENTES DE CONTROLE DE TIRO DE AERONAVES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1280,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'COMPONENTES DE CONTROLE DE TIRO EM AERONAVES DE BOMBARDEIO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1285,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTO RADAR DE CONTROLE DE TIRO (EXCETO DE AERONAVES)',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1287,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTO SONAR DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1290,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTOS DIVERSOS DE CONTROLE DE TIRO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1295,
  'codigoGrupo': 12,
  'nomeGrupo': 'EQUIPAMENTOS DE TIRO',
  'nomeClasse': 'EQUIPAMENTO DE CONTROLE DE TIRO DIVERSOS',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1305,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MUNIÇÃO DE CALIBRE ATÉ 30 MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1310,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 30 MM ATÉ 75 MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1315,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 75MM ATÉE 125MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1320,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MUNIÇÃO DE CALIBRE ACIMA DE 125 MM',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1325,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'BOMBAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1330,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'GRANADAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1336,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'OGIVAS E COMPONENTES EXPLOSIVOS DE MISSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1337,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'UNIDADES DE PROPULSAO EXPLOSIVA A COMBUSTIVEL SOLIDO DE VEICULOS ESPACIAIS E MISSEIS GUIADOS E SEUS COMPONENTES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1338,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'UNIDADES DE PROPULSAO INERTES A COMBUSTIVEL SOLIDO DE VEICULOS ESPACIAIS E MISSEIS GUIADOS E SEUS COMPONENTES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1340,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'ROJÕES, FOGUETES, MUNIÇÃO E COMPONENTES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1345,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MINAS TERRESTRES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1346,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MUNIÇÕES DE CONTROLE À DISTÂNCIA',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1350,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES INERTES DE MINA SUBMARINA',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1351,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES EXPLOSIVOS DE MINAS SUBMARINAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1352,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'DISPOSITIVOS INERTES DE MINAS SUBAQUÁTICAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1353,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'DISPOSITIVOS EXPLOSIVOS DE MINAS SUBAQUÁTICAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1355,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES INERTES DE TORPEDOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1356,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES EXPLOSIVOS DE TORPEDOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1360,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES INERTES DE CARGAS DE PROFUNDIDADE',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1361,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES EXPLOSIVOS DE BOMBAS DE PROFUNDIDADE',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1367,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'CONJUNTOS E EQUIPAMENTOS TÁTICOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1370,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'PIROTECNICOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1375,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'MATERIAIS DE DEMOLIÇÃO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1376,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'EXPLOSIVOS A GRANEL',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1377,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'DISPOSITIVOS ACIONADOS POR PROPELENTES E CARTUCHOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1380,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'AGENTES BIOLOGICOS DE USO MILITAR',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1385,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'EQUIPAMENTOS E FERRAMENTAS PARA MANUSEIO DE EXPLOSIVO NA SU-PERFÍCIE',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1386,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'EQUIPAMENTOS E FERRAMENTAS PARA MANUSEIO DE  EXPLOSIVO  SUB-MERSO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1390,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'ESPOLETAS E ESTOPILHAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1395,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'COMPONENTES DIVERSOS DE MUNIÇÃO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1398,
  'codigoGrupo': 13,
  'nomeGrupo': 'MUNIÇÕES E EXPLOSIVOS',
  'nomeClasse': 'EQUIPAMENTOS ESPECIALIZADOS PARA MANUSEIO E CONSERVACAO DE MUNICAO',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1410,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1420,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'COMPONENTES DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1425,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'SISTEMAS COMPLETOS DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1427,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'SUBSISTEMAS DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1430,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'SISTEMA DE CONTROLE REMOTO DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1440,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'LANÇADORES DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1450,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'EQUIPAMENTO PARA MANUSEIO DE MANUTENÇÃO DE MÍSSEIS GUIADOS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1495,
  'codigoGrupo': 14,
  'nomeGrupo': 'MÍSSEIS GUIADOS',
  'nomeClasse': 'MISSEIS GUIADOS DIVERSOS',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1505,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'AERONAVES',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1510,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'AERONAVES DE ASAS FIXAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1515,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'HELICES DE AERONAVES E COMPONENTES',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1520,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'AERONAVES DE ASA ROTATIVAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1525,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'COMPONENTES DE SISTEMA DE FREIOS E RODAS',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1530,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'COMPNENTES DE SISTEMA HIDRAULICO, DE VACUO E  DEGELAMENTO',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1535,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'COMPONENTE DE SISTEMAS DE CONDICIONAMENTO  DE  AR,DO AQUECIMENTO E DE PRESSURIZACAO',
  'statusClasse': False,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1540,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'PLANADORES',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1550,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'AERONAVES TELEGUIADAS',
  'statusClasse': True,
  'dataHoraAtualizacao': '2021-10-16T09:17:13.045775'},
 {'codigoClasse': 1560,
  'codigoGrupo': 15,
  'nomeGrupo': 'AERONAVES E SEUS COMPONENTES ESTRUTURAIS',
  'nomeClasse': 'COMPONENTES ESTRUTURAIS DE AERONAVES',

4. Recuperar o resultado e armazenar em uma variável

In [6]:
df_resultado_classe = pd.DataFrame(resultado_classe)

5. Vamos colocar em um Data Frame

In [7]:
df_resultado_classe

,codigoClasse,codigoGrupo,nomeGrupo,nomeClasse,statusClasse,dataHoraAtualizacao
0,1005,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ATÉ 120MM,True,2021-10-16T09:17:13.045775
1,1010,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 30MM ATÉ 75MM,True,2021-10-16T09:17:13.045775
2,1015,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 75MM ATÉ 125MM,True,2021-10-16T09:17:13.045775
3,1020,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 125MM ATÉ 150MM,True,2021-10-16T09:17:13.045775
4,1025,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 150MM ATÉ 200MM,True,2021-10-16T09:17:13.045775
...,...,...,...,...,...,...
706,7120,71,MOBILIÁRIOS,ESTANTES E ARMACOES PARA ALMOXARIFADOS,False,2021-10-16T09:17:13.045775
707,7432,74,"MÁQUINAS PARA ESCRITÓRIO, SISTEMAS DE PROCESSA...",MAQUINAS DE REPROGRAFIA,False,2021-10-16T09:17:13.045775
708,2315,23,VEíCULOS,VEICULOS DE SERVICOS ESPECIAIS,False,2021-10-16T09:17:13.045775
709,6040,60,"MATERIAIS, COMPONENTES, CONJUNTOS E ACESSÓRIOS...",SENSORES DE FIBRA OTICA,False,2021-10-16T09:17:13.045775
710,6460,64,"MEDICAMENTOS, DROGAS E PRODUTOS BIOLOGICOS",MEDICAMENTOS PARA AGENTES DIAGNOSTICOS,False,2021-10-16T09:17:13.045775

6. Análise Macro do Data Frame

In [8]:
df_resultado_classe.info()

<class 'pandas.DataFrame'>
RangeIndex: 711 entries, 0 to 710
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   codigoClasse         711 non-null    int64
 1   codigoGrupo          711 non-null    int64
 2   nomeGrupo            711 non-null    str
 3   nomeClasse           711 non-null    str
 4   statusClasse         711 non-null    bool
 5   dataHoraAtualizacao  711 non-null    str
dtypes: bool(1), int64(2), str(3)
memory usage: 103.8 KB

In [9]:
display(df_resultado_classe)

df_resultado_classe['dataHoraAtualizacao'] = pd.to_datetime(df_resultado_classe['dataHoraAtualizacao'])

df_resultado_classe['dataCarga'] = pd.to_datetime('today').normalize()

display(df_resultado_classe)

,codigoClasse,codigoGrupo,nomeGrupo,nomeClasse,statusClasse,dataHoraAtualizacao
0,1005,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ATÉ 120MM,True,2021-10-16T09:17:13.045775
1,1010,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 30MM ATÉ 75MM,True,2021-10-16T09:17:13.045775
2,1015,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 75MM ATÉ 125MM,True,2021-10-16T09:17:13.045775
3,1020,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 125MM ATÉ 150MM,True,2021-10-16T09:17:13.045775
4,1025,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 150MM ATÉ 200MM,True,2021-10-16T09:17:13.045775
...,...,...,...,...,...,...
706,7120,71,MOBILIÁRIOS,ESTANTES E ARMACOES PARA ALMOXARIFADOS,False,2021-10-16T09:17:13.045775
707,7432,74,"MÁQUINAS PARA ESCRITÓRIO, SISTEMAS DE PROCESSA...",MAQUINAS DE REPROGRAFIA,False,2021-10-16T09:17:13.045775
708,2315,23,VEíCULOS,VEICULOS DE SERVICOS ESPECIAIS,False,2021-10-16T09:17:13.045775
709,6040,60,"MATERIAIS, COMPONENTES, CONJUNTOS E ACESSÓRIOS...",SENSORES DE FIBRA OTICA,False,2021-10-16T09:17:13.045775
710,6460,64,"MEDICAMENTOS, DROGAS E PRODUTOS BIOLOGICOS",MEDICAMENTOS PARA AGENTES DIAGNOSTICOS,False,2021-10-16T09:17:13.045775

,codigoClasse,codigoGrupo,nomeGrupo,nomeClasse,statusClasse,dataHoraAtualizacao,dataCarga
0,1005,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ATÉ 120MM,True,2021-10-16 09:17:13.045775,2026-08-08
1,1010,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 30MM ATÉ 75MM,True,2021-10-16 09:17:13.045775,2026-08-08
2,1015,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 75MM ATÉ 125MM,True,2021-10-16 09:17:13.045775,2026-08-08
3,1020,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 125MM ATÉ 150MM,True,2021-10-16 09:17:13.045775,2026-08-08
4,1025,10,ARMAMENTO,ARMAS DE FOGO DE CALIBRE ACIMA DE 150MM ATÉ 200MM,True,2021-10-16 09:17:13.045775,2026-08-08
...,...,...,...,...,...,...,...
706,7120,71,MOBILIÁRIOS,ESTANTES E ARMACOES PARA ALMOXARIFADOS,False,2021-10-16 09:17:13.045775,2026-08-08
707,7432,74,"MÁQUINAS PARA ESCRITÓRIO, SISTEMAS DE PROCESSA...",MAQUINAS DE REPROGRAFIA,False,2021-10-16 09:17:13.045775,2026-08-08
708,2315,23,VEíCULOS,VEICULOS DE SERVICOS ESPECIAIS,False,2021-10-16 09:17:13.045775,2026-08-08
709,6040,60,"MATERIAIS, COMPONENTES, CONJUNTOS E ACESSÓRIOS...",SENSORES DE FIBRA OTICA,False,2021-10-16 09:17:13.045775,2026-08-08
710,6460,64,"MEDICAMENTOS, DROGAS E PRODUTOS BIOLOGICOS",MEDICAMENTOS PARA AGENTES DIAGNOSTICOS,False,2021-10-16 09:17:13.045775,2026-08-08

In [11]:
df_resultado_classe.to_csv('data.csv')

df_resultado_classe.to_parquet('data.parquet')